
import { StyleSheet } from 'react-native';

// Light mode colors
export const lightColors = {
  background: '#F5F5F5',
  text: '#1A1A1A',
  textSecondary: '#666666',
  primary: '#38761d',
  secondary: '#f4c430',
  accent: '#3498db',
  card: '#FFFFFF',
  highlight: '#e67e22',
  border: '#E0E0E0',
  success: '#22c55e',
  error: '#ef4444',
  white: '#FFFFFF',
  black: '#1A1A1A',
};

// Dark mode colors
export const darkColors = {
  background: '#121212',
  text: '#FFFFFF',
  textSecondary: '#B0B0B0',
  primary: '#4CAF50',
  secondary: '#FFD54F',
  accent: '#64B5F6',
  card: '#1E1E1E',
  highlight: '#FF9800',
  border: '#333333',
  success: '#66BB6A',
  error: '#EF5350',
  white: '#FFFFFF',
  black: '#000000',
};

// Default to light colors for backwards compatibility
export const colors = lightColors;

export const buttonStyles = StyleSheet.create({
  primary: {
    backgroundColor: lightColors.primary,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondary: {
    backgroundColor: lightColors.secondary,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryText: {
    color: lightColors.black,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  accent: {
    backgroundColor: lightColors.accent,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outline: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: lightColors.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  text: {
    color: lightColors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  textOutline: {
    color: lightColors.primary,
    fontSize: 16,
    fontWeight: '600',
  },
});

export const commonStyles = StyleSheet.create({
  wrapper: {
    backgroundColor: lightColors.background,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    backgroundColor: lightColors.background,
    width: '100%',
    height: '100%',
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    maxWidth: 800,
    width: '100%',
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    textAlign: 'center',
    color: lightColors.text,
    marginBottom: 12,
  },
  subtitle: {
    fontSize: 20,
    fontWeight: '700',
    color: lightColors.text,
    marginBottom: 10,
  },
  text: {
    fontSize: 16,
    fontWeight: '400',
    color: lightColors.text,
    marginBottom: 8,
    lineHeight: 24,
  },
  textSecondary: {
    fontSize: 14,
    fontWeight: '400',
    color: lightColors.textSecondary,
    lineHeight: 20,
  },
  section: {
    width: '100%',
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  card: {
    backgroundColor: lightColors.card,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  cardWhite: {
    backgroundColor: lightColors.white,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1,
    borderColor: lightColors.border,
  },
  input: {
    backgroundColor: lightColors.white,
    borderWidth: 1,
    borderColor: lightColors.border,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    color: lightColors.text,
    marginBottom: 16,
  },
  inputMultiline: {
    backgroundColor: lightColors.white,
    borderWidth: 1,
    borderColor: lightColors.border,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    color: lightColors.text,
    marginBottom: 16,
    minHeight: 100,
    textAlignVertical: 'top',
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: lightColors.text,
    marginBottom: 6,
  },
  divider: {
    height: 1,
    backgroundColor: lightColors.border,
    marginVertical: 16,
  },
  badge: {
    backgroundColor: lightColors.primary,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  badgeText: {
    color: lightColors.white,
    fontSize: 12,
    fontWeight: '600',
  },
});
